/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface": "#121413",
        "surface-dim": "#121413",
        "surface-bright": "#383a38",
        "surface-container-lowest": "#0d0f0e",
        "surface-container-low": "#1a1c1b",
        "surface-container": "#1e201f",
        "surface-container-high": "#282a29",
        "surface-container-highest": "#333534",
        "on-surface": "#e2e3e0",
        "on-surface-variant": "#c1c8c3",
        "inverse-surface": "#e2e3e0",
        "inverse-on-surface": "#2f3130",
        "outline": "#8b928d",
        "outline-variant": "#424844",
        "surface-tint": "#adcebd",
        "primary": "#adcebd",
        "on-primary": "#18362a",
        "primary-container": "#2d4b3e",
        "on-primary-container": "#99baa9",
        "inverse-primary": "#466557",
        "secondary": "#c6c7c5",
        "on-secondary": "#2f3130",
        "secondary-container": "#454746",
        "on-secondary-container": "#b5b5b3",
        "tertiary": "#c3c7c4",
        "on-tertiary": "#2d312f",
        "tertiary-container": "#414643",
        "on-tertiary-container": "#afb3b0",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#c8ead8",
        "primary-fixed-dim": "#adcebd",
        "on-primary-fixed": "#012116",
        "on-primary-fixed-variant": "#2f4d40",
        "secondary-fixed": "#e2e3e0",
        "secondary-fixed-dim": "#c6c7c5",
        "on-secondary-fixed": "#1a1c1b",
        "on-secondary-fixed-variant": "#454746",
        "tertiary-fixed": "#e0e3df",
        "tertiary-fixed-dim": "#c3c7c4",
        "on-tertiary-fixed": "#181d1a",
        "on-tertiary-fixed-variant": "#434845",
        "background": "#121413",
        "on-background": "#e2e3e0",
        "surface-variant": "#333534",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "md": "0.5rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "gutter": "24px",
        "margin-desktop": "64px",
        "margin-mobile": "20px",
        "stack-xl": "120px",
        "stack-md": "64px",
        "container-max": "1280px"
      },
      fontFamily: {
        sans: ["Inter", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        display: ["'Hanken Grotesk'", "sans-serif"],
        headline: ["'Hanken Grotesk'", "sans-serif"],
        body: ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl": ["'Hanken Grotesk'", "sans-serif"],
        "headline-lg": ["'Hanken Grotesk'", "sans-serif"],
        "display-lg": ["'Hanken Grotesk'", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["64px", { lineHeight: "72px", letterSpacing: "-0.04em", fontWeight: "600" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
